### ISSUE TITLE
Query: Can the transport be HTTPS?

### ISSUE THREAD

**Issue by sudharsanmit** [viruschidai/validate-vat#11]
Is VAT number sent as plain text over HTTP? Is it not a security flaw?

**Comment by viruschidai** [comment]
I think the EU SOAP service does not support `https`.

**Comment by sudharsanmit** [comment]
vatlayer advertises that it supports https. If the govt provided SOAP api is http, I don't know how vatlayer claims so!

**Comment by viruschidai** [comment]
I'll close this for now since we cannot do anything now.
