### ISSUE TITLE
Just getting following error: Failed to parseField countryCode

### ISSUE THREAD

**Issue by arminschleicher** [viruschidai/validate-vat#12]
You can check out the error here. 
https://runkit.com/58860a360629220014e32905/58860a360629220014e32907

Has the SOAP Response changed? Thanks and kind regards

**Comment by arminschleicher** [comment]
Problem is caused by the EUROPA Service, which is currently down, they just issued a report. Please close the issue and thanks for your work :)

**Comment by viruschidai** [comment]
np :)

**Comment by arminschleicher** [comment]
...hm, service is up again, for invalid VAT numbers everything works as expected - valid ones throw an  "unknown error" exception. Looks like they indeed changed the response? Would be great if you can have a look at it:

https://runkit.com/58860a360629220014e32905/58860a360629220014e32907

<img width="641" alt="bildschirmfoto 2017-01-24 um 08 27 34" src="https://cloud.githubusercontent.com/assets/4428052/22237960/1ed3a8fe-e20f-11e6-9aca-6668c4767391.png">
