### ISSUE TITLE
Use Promise

### ISSUE THREAD

**Issue by avetisk** [viruschidai/validate-vat#16]
Or at least provide a Promise API :)

**Comment by viruschidai** [comment]
I was thinking to make this work in both browser & node.js environment if there is interests.

**Comment by BlackRoman** [comment]
You can simply use `bluebird.promisify()` or `bluebird.promisifyAll()` for promisification.

**Comment by bluemanos** [comment]
@BlackRoman or you an use standard `Promise` function - without attaching another js library.

```js
                return new Promise((resolve, reject) => {
                    validateVat(req.body.country_code, req.body.vat_number, (err, validationInfo) => {
                        if (err !== null) {
                            reject(err);
                        }

                        if (validationInfo !== undefined && validationInfo.valid === false) {
                            reject(new Error('The VAT number do not exists in European Union'));
                        }

                        resolve(validationInfo);
                    });
                });
```

**Comment by benbucksch** [comment]
Fixed in https://github.com/benbucksch/validate-vat == https://github.com/viruschidai/validate-vat/pull/28

**Comment by viruschidai** [comment]
Use this https://github.com/viruschidai/validate-vat-ts which supports `await`
