### ISSUE TITLE
Error: The VAT database of the requested member country is unavailable, please try again later

### ISSUE THREAD

**Issue by jirikrepl** [viruschidai/validate-vat#18]
For the VAT GB227784183 I got this error:

`Error: The VAT database of the requested member country is unavailable, please try again later`

Is the database for the GB really unavailable? Or they VIES changed something in their API?

when I got that error above, I got also the same response from here:
<img width="1109" alt="screen shot 2019-01-22 at 13 14 20" src="https://user-images.githubusercontent.com/2588479/51538789-7b855d00-1e52-11e9-8272-a3fe9c819f6e.png">

After while both in my app and on that website it started working:
<img width="2032" alt="screen shot 2019-01-22 at 14 27 25" src="https://user-images.githubusercontent.com/2588479/51538794-7de7b700-1e52-11e9-9b29-c77cd0c5ecf0.png">

**Comment by viruschidai** [comment]
From my understanding, each country in EU has their own VAT database and server, occasionally the server may not be available due to maintenance.

**Comment by jirikrepl** [comment]
We had browser test on circle ci (which tested form with VAT field) and in the last month until recently, it was unavailable for a lot of times.

**Comment by viruschidai** [comment]
If it happens on the official EU vat validation site, I don't think it is an API issue. Next time when you see the error, maybe check the status here http://ec.europa.eu/taxation_customs/vies/vatRequest.htmlto see if the GB db is out of service
