### ISSUE TITLE
Can i use async/await instead of cabllback?

### ISSUE THREAD

**Issue by ghost** [viruschidai/validate-vat#26]
Hello,

In your example:
`var validate = require('validate-vat');
validate( 'xx',  'xxxxxxx',  function(err, validationInfo) {
    console.log(validationInfo);
});
`
You use the callback. but can i use the validate with async/await feature? Thank you

**Comment by benbucksch** [comment]
See #16 

Fixed in https://github.com/benbucksch/validate-vat == https://github.com/viruschidai/validate-vat/pull/28

**Comment by familiadalousa** [comment]
the npm install --save https://github.com/benbucksch/validate-vat does not work anymore.....

**Comment by thebillg** [comment]
try this https://github.com/viruschidai/validate-vat-ts
