### ISSUE TITLE
How to process other countries

### ISSUE THREAD

**Issue by koesper** [viruschidai/validate-vat#30]
The VIES check is only usable for EU countries, which makes complete sense.
I was wondering what would be the best way to process other countrycodes.

For instance, CHE100416306IVA is not valid according to the VIES check, but it might very well be valid. (Switzerland is in europe, but not in the EU)

Should i check the countrycodes beforehand? or is this something we should incorperate into this module?

**Comment by gempain** [comment]
I think this is out of the scope of this module. The VIES service, as you rightly said, only makes sense for EU VAT numbers. Switzerland not being part of the EU, whatever VAT number they are using is out of the jurisdiction of the EU (as an organization). Switzerland (or any country with a VAT that is not an EU state member) probably provides its own validation service.

**Comment by viruschidai** [comment]
what @gempain said is true. This module just simplify the call to the EU VIES SOAP server, whatever countries are supported by EU VIES SOAP server is out of control of this module.
