### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by ghost** [viruschidai/validate-vat#31]
Hello,

The install is not working!
 npm install --save https://github.com/benbucksch/validate-vat
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/benbucksch/validate-vat.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.

I tried this for testing:
curl https://github.com/benbucksch/validate-vat.git
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

Any help?

**Comment by familiadalousa** [comment]
can be fixed using npm i --save validate-vat

**Comment by familiadalousa** [comment]
Wrong... i made confusion with version. The install 

> npm install --save https://github.com/benbucksch/validate-vat

Returns the error:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/benbucksch/validate-vat.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by viruschidai** [comment]
if you want to use es6 or typescript, please use github.com/viruschidai/validate-vat-ts
