### ISSUE TITLE
CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by giorgiocarniel** [viruschidai/validate-vat#38]
Is It usable with ReactJS?

I'm trying to validate a VAT Number with the following code, but I get the `'Access-Control-Allow-Origin'` error.
Is there a way to solve it in the frontend, or Am I constrained to do the call in the backend?

```
import validate from 'validate-vat';

validate('IT',  'XXXXXXXXXXX',  function(err, validationInfo) {
    console.log("err", err);
    console.log("validationInfo", validationInfo);
});
```

Error:
![image](https://user-images.githubusercontent.com/69838480/91873791-c34ca700-ec79-11ea-87d0-c0b4cd58c884.png)

Thanks

**Comment by thebillg** [comment]
No, the EU Vat server has Cors controls in browser.

**Comment by RosiersRobin** [comment]
I'm having the following error:

```
Access to fetch at 'https://ec.europa.eu/taxation_customs/vies/services/checkVatService' from origin 'http://mydomain.local' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I have exactly the same error on my server. Running latest Laravel version and the latest version of your package. How to fix this then?

**Comment by Lewitje** [comment]
I have the same CORS error

**Comment by viruschidai** [comment]
@RosiersRobin on server side, you can config your http client to ignore cors header.

**Comment by viruschidai** [comment]
Close this since this is how the EU vat server works.
