### ISSUE TITLE
consult number

### ISSUE THREAD

**Issue by yumminova** [viruschidai/validate-vat#8]
Hi,

for legal purposes this check is awesome as its one of the vew that included the businessname.
People think that thats not needed but it actually is.

When u do the request u should also post your own Tax id to get a consulation code, a identifier that proves that u checked the data.

Can that be implemented?

**Comment by thebillg** [comment]
This lib is simply calling the VIES service. I dont think they would store your usage. You have to do it by yourself if you really need to.
